create table if not exists page (id int unsigned NOT NULL AUTO_INCREMENT, title varchar (256), url varchar (256), createdate datetime , modifieddate datetime , publishdate datetime , markfordelete char (1), primary key(id)) ENGINE=InnoDB;
create table if not exists pagefragment (id int unsigned NOT NULL AUTO_INCREMENT, title varchar (50), html text , position tinyint , primary key(id)) ENGINE=InnoDB;
create table if not exists fragmenttype (id tinyint unsigned NOT NULL AUTO_INCREMENT, title varchar (50), name varchar (20), primary key(id)) ENGINE=InnoDB;
create table if not exists loginuser (id tinyint unsigned NOT NULL AUTO_INCREMENT, first_name varchar (50), last_name varchar (50), user_name varchar (50), password varchar (50), primary key(id)) ENGINE=InnoDB;
create table if not exists pagetemplate (id tinyint unsigned NOT NULL AUTO_INCREMENT, title varchar (50), html text , primary key(id)) ENGINE=InnoDB;
create table if not exists page_map_pagefragment (id int unsigned NOT NULL AUTO_INCREMENT,pageid int unsigned NOT NULL,pagefragmentid int unsigned NOT NULL,FOREIGN KEY (`pageid`) REFERENCES `page` (`id`),FOREIGN KEY (`pagefragmentid`) REFERENCES `pagefragment` (`id`), primary key (id)) ENGINE=InnoDB;
create table if not exists page_map_pagetemplate (id int unsigned NOT NULL AUTO_INCREMENT,pageid int unsigned NOT NULL,pagetemplateid tinyint unsigned NOT NULL,FOREIGN KEY (`pageid`) REFERENCES `page` (`id`),FOREIGN KEY (`pagetemplateid`) REFERENCES `pagetemplate` (`id`), primary key (id)) ENGINE=InnoDB;
create table if not exists pagefragment_map_fragmenttype (id int unsigned NOT NULL AUTO_INCREMENT,pagefragmentid int unsigned NOT NULL,fragmenttypeid tinyint unsigned NOT NULL,FOREIGN KEY (`pagefragmentid`) REFERENCES `pagefragment` (`id`),FOREIGN KEY (`fragmenttypeid`) REFERENCES `fragmenttype` (`id`), primary key (id)) ENGINE=InnoDB;
SET FOREIGN_KEY_CHECKS=0;
truncate pagetemplate;
SET FOREIGN_KEY_CHECKS=1;
insert into pagetemplate (title,html) values ('Blog post','html - blog post'),('Blog post 2','html - blog post 2');
SET FOREIGN_KEY_CHECKS=0;
truncate loginuser;
SET FOREIGN_KEY_CHECKS=1;
insert into loginuser (first_name,last_name,user_name,password) values ('Poker','John','poker','john');
SET FOREIGN_KEY_CHECKS=0;
truncate fragmenttype;
SET FOREIGN_KEY_CHECKS=1;
insert into fragmenttype (title,name) values ('Rich Text','richText');
